disabled_rules:
    - line_length
    - trailing_whitespace
    - force_cast
    - colon
    - variable_name
    - legacy_constructor
    - type_name
    - control_statement
    - force_try
    - function_parameter_count
    - valid_docs
    - void_return
    - fallthrough
    - empty_parentheses_with_trailing_closure
    - for_where
    - private_over_fileprivate
    - discarded_notification_center_observer
    - unused_closure_parameter
    - large_tuple
    - cyclomatic_complexity
    - redundant_string_enum_value
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - JanePresentationUITests
    - fastlane
type_body_length:
    warning: 600
    error: 1200
function_body_length:
    warning: 80
file_length:
    warning: 750
    error: 1200

switch_case_alignment:
    indented_cases: true
